### ISSUE TITLE
Implementation of SX gate

### ISSUE THREAD

**Issue by LiranShirizly** [qiskit-community/lindbladmpo#12]
Hi,

Is there an option to implement gates using this solver, especially the SX gate? 
If not, can it be added?

Thanks

**Comment by haggaila** [comment]
The current version supports some gates with the `apply_gates` parameter. The SX gate still awaits an implementation.

**Comment by haggaila** [comment]
@LiranShirizly the SX gate has been added (together with a few others).
Check `apply_gates` in the [API help](https://github.com/qiskit-community/lindbladmpo/blob/main/docs/API_DOCS.md).
@gregoire-misguich - closing.
